import AIPluginInterface from './AIPlugin.interface.js';

/**
 * Sample Built-In Plugin: Markdown Export Connector
 */
class MarkdownExportPlugin extends AIPluginInterface {
  constructor() {
    super({
      id: 'plugin-markdown-export',
      name: 'Markdown Export Connector',
      version: '1.0.0',
      author: 'NexBlog Engineering',
      permissions: ['content:read'],
      capabilities: ['export-markdown'],
    });
  }

  async execute(capability, params = {}) {
    if (capability !== 'export-markdown') {
      throw new Error(`Capability ${capability} unsupported`);
    }
    const { title = 'Article', content = '' } = params;
    return `# ${title}\n\n*Generated by AI Operating System*\n\n---\n\n${content}`;
  }
}

/**
 * PluginManager
 * Manages plugin lifecycle, permission boundaries, capabilities registry, and health monitoring.
 */
class PluginManager {
  constructor() {
    this.plugins = new Map(); // id -> AIPlugin instance
    this._registerSamplePlugins();
  }

  _registerSamplePlugins() {
    const mdPlugin = new MarkdownExportPlugin();
    this.registerPlugin(mdPlugin);
  }

  /**
   * Register a verified plugin instance into the OS.
   * @param {AIPluginInterface} plugin
   */
  registerPlugin(plugin) {
    if (!plugin || !plugin.manifest || !plugin.manifest.id) {
      throw new Error('PluginManager: Invalid plugin instance or manifest');
    }
    this.plugins.set(plugin.manifest.id, plugin);
  }

  /**
   * Retrieve plugin by ID
   */
  getPlugin(pluginId) {
    return this.plugins.get(pluginId) || null;
  }

  /**
   * List all registered plugins and their capabilities
   */
  listPlugins() {
    return Array.from(this.plugins.values()).map((p) => ({
      ...p.manifest,
      status: p.status,
    }));
  }

  /**
   * Execute a specific capability across registered plugins or on a target plugin ID
   */
  async executePlugin(pluginId, capability, params = {}) {
    const plugin = this.getPlugin(pluginId);
    if (!plugin) {
      throw new Error(`Plugin not registered: ${pluginId}`);
    }
    return plugin.execute(capability, params);
  }

  /**
   * Run diagnostic health probe across all registered plugins
   */
  async getDiagnostics() {
    const results = {};
    for (const [id, plugin] of this.plugins.entries()) {
      try {
        results[id] = await plugin.checkHealth();
      } catch (err) {
        results[id] = { status: 'error', message: err.message };
      }
    }
    return results;
  }
}

export const pluginManager = new PluginManager();
export default pluginManager;
